name: FactApi Build
on:
  push:
    branches: [ user/trung/publish-to-dockerhub ]
    #paths: 
    #  - 'src/services/facts/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: $(date +%s)
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/services/facts/SleepyShark.Nutrition.FactApi/SleepyShark.Nutrition.FactApi.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal src/services/facts/SleepyShark.Nutrition.FactApi/SleepyShark.Nutrition.FactApi.csproj
    - name: Publish
      run: dotnet publish --no-restore src/services/facts/SleepyShark.Nutrition.FactApi/SleepyShark.Nutrition.FactApi.csproj -c Release -o artifact
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: 'letrung'
        password: 'a6bddf28-1554-4d43-851f-572c2935a7f7'
    - name: Build the Docker image
      run: docker build . --file src/services/facts/SleepyShark.Nutrition.FactApi/Dockerfile --tag letrung/sleepyshark.nutrition.factapi:${{env.IMAGE_TAG}}
    - name: Push the Docker image to registry
      run: docker push letrung/sleepyshark.nutrition.factapi:${{env.IMAGE_TAG}}
    - uses: actions/upload-artifact@v2
      with:
        name: factapi-artifact
        path: artifact