name: FactApi Build
on:
  push:
    branches: [ user/trung/sample-build-action ]
    paths: 
      - 'src/services/facts/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/services/facts/SleepyShark.Nutrition.FactApi/SleepyShark.Nutrition.FactApi.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal src/services/facts/SleepyShark.Nutrition.FactApi/SleepyShark.Nutrition.FactApi.csproj
    - name: Publish
      run: dotnet publish --no-restore src/services/facts/SleepyShark.Nutrition.FactApi/SleepyShark.Nutrition.FactApi.csproj -c Release -o artifact
    - uses: actions/upload-artifact@v2
      with:
        name: factapi-artifact
        path: artifact
